dist: bionic
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
  - pipenv run pytest
after_success:
  - pipenv run coveralls

# deploy:
#   provider: pypi
#   user: "ordina-pythoneers"
#   password:
#     secure: LongStringThatNeedsToBeSetByRoel
#   # (travis encrypt PYTHONEERS-PASSWORD --com --add deploy.password)
#   on:
#     tags: true
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
